[package]
name = "cproxy"
version = "4.1.6"
authors = ["Xiangru Lian <admin@mail.xrlian.com>"]
description = "Transparent proxy built on cgroup net_cls."
homepage = "https://github.com/NOBLES5E/cproxy"
license = "AGPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4.0", features = ["derive", "env"] }
cgroups-rs = "0.2"
cmd_lib = "1.3"
ctrlc = "3.2"
flume = "0.10"
nix = "0.26"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
with_drop = "0.0.3"
